spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23licG80jOjet85bNJ
            client-secret: 606f046ad4fc4e3cb4cee5f0b65879fc04e5e777
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
